import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { WagmiConfig, createClient } from 'wagmi'
import { getDefaultProvider } from 'ethers'
import { useAccount, useBalance, useConnect, useDisconnect } from 'wagmi'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { Box, Button, Card, CardBody, CardFooter, Heading, Text } from '@chakra-ui/react'

const client = createClient({
  autoConnect: false,
  provider: getDefaultProvider(),
})

export default function Home() {

  return (
    <>
      <Head>
        <title>Wagmi - Connect Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box>
          <WagmiConfig client={client}>
            <Profile />
          </WagmiConfig>
        </Box>
      </main>
    </>
  )
}

function Profile() {
  const { address, isConnected } = useAccount()
  const { data, isError, isLoading } = useBalance({
    address
  })
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  })
  const { disconnect } = useDisconnect()

  return (
    <Card align="center" bg="teal.300">
      <CardBody>
        <Text align="center">Connected to:</Text>
        <Heading size='md' color="white">{address}</Heading>
        <Text align="center">Balance to:</Text>
        {isLoading && <Text align="center">...</Text>}
        {data && <Heading size='md' color="white">{data?.formatted} {data?.symbol}</Heading>}
      </CardBody>
      <CardFooter>
        {isConnected ? <Button onClick={() => disconnect()}>Disconnect</Button> : <Button onClick={() => connect()}>Connect Wallet</Button>}
      </CardFooter>
    </Card>
  )
}